### ISSUE TITLE
Who is Logesh ?

### ISSUE THREAD

**Issue by dikshit-n** [jagadheesh6/fitness-webapp#3]
I was wondering by seeing the name @logeshdk in this repository. How much commits does he push ? 
As my front end assistant,  I didn't give any works for him. This is my mistake I think. What is your view @jagadheesh6

**Comment by jaga-live** [comment]
Lol, he's a motivational contributor

**Comment by dikshit-n** [comment]
Yeah ! acceptable answer 🐱
